### PR TITLE
Relax `pyarrow` pin

### LINKED ISSUE #390: loosen, update, or widen pyarrow dependencies
databricks-sql-connector 3.1.2 has `Requires-Dist: pyarrow (>=14.0.1,<15.0.0)`

I know that's a "major version", but pyarrow releases "major versions" often, and as of this writing [16.1.0](https://pypi.org/project/pyarrow/16.1.0/) is the latest, with databricks-sql-connector being 2 major versions behind.  Since pyarrow is a very widely used dependency having this narrow dependency constraint can make resolution difficult to impossible.

### PR DESCRIPTION
**Pull request by dhirschfeld**
Arrow 15 has been released and it woudl be good to be able to use it.

https://arrow.apache.org/blog/2024/01/21/15.0.0-release/

----

Resolves #390

### CODE REVIEW

**Comment by kravets-levko** [comment]
Hi @dhirschfeld! Thank you for contributing!  I should ask you to do two things before we can proceed:

- please [sign off your commits](https://github.com/databricks/databricks-sql-python/blob/main/CONTRIBUTING.md#sign-your-work). To fix existing comits in this branch - use `git rebase -i main`
- please update `poetry.lock` file as well using `poetry lock` command

**Comment by dhirschfeld** [comment]
> *please sign off your commits*

In the linked docs it says:
> *you can sign your commit automatically with `git commit -s`*

...but my commits are cryptographically signed, so do I still need the *Signed-off-by:* footer?


image

**Comment by dhirschfeld** [comment]
@kravets-levko - the commits should all be signed off now...

**Comment by dhirschfeld** [comment]
ping @kravets-levko - any objections?

**Comment by susodapop** [comment]
> ...but my commits are cryptographically signed, so do I still need the Signed-off-by: footer?

Hey @dhirschfeld this is a bit tangential to your PR but in case your curious: the cryptographic signing and the `Signed-off-by` commit text actually serve different purposes. The "verified" badge verifies that it was your computer that generated the code. Whereas the `Signed-off-by` header is more about legal attribution. The "verified" header is nice to have but not required by this repository. The `Signed-off-by` is mandatory to protect the maintainers from legal challenges if someone attempts to commit code to this repository that they weren't authorized to open-source.

**Comment by susodapop** [comment]
Note that this PR will also close https://github.com/databricks/databricks-sql-python/issues/390

**Review by susodapop — APPROVED** [review]
Assuming this passes the automated e2e tests this looks good to merge.

**Review by kravets-levko — APPROVED** [review]

**Pull request merged**
