### PR TITLE
Bump version to 2.8.0

### PR DESCRIPTION
**Pull request by susodapop**
This is a MINOR release because it includes new functionality (Cloud Fetch, namely)

### CODE REVIEW

**Review by rcypher-databricks — APPROVED** [review]

**Comment by ncapeta** [comment]
Is there a expected release date ? would be great to have it

**Comment by susodapop** [comment]
It will go up today.

**Comment by susodapop** [comment]
v2.8.0 is deploying to Pypi now @ncapeta

**Comment by ncapeta** [comment]
Appreciated !

**Pull request merged**
