### PR TITLE
[Internal] Less strict numpy and pyarrow dependencies

### PR DESCRIPTION
**Pull request by susodapop**
This is a clone of #74. 

Poetry uses the `poetry.lock` file to actually install dependencies. Updating `pyproject.toml` alone is not sufficient to actually test the library.  To make this PR I:

1. Checked-out #74
2. Rebased onto `main`
3. `rm poetry.lock`
4. `poetry install`
5. Committed the changes to `poetry.lock`

### CODE REVIEW

**Comment by Tom-Newton** [comment]
Any progress on running the end to end tests @susodapop ?

**Comment by susodapop** [comment]
Thanks for the ping!

**Comment by Tom-Newton** [comment]
Thanks @susodapop. Any idea when the next release will be I'm quite keen to use this 🙂

**Comment by susodapop** [comment]
@Tom-Newton It should be out later today once https://github.com/databricks/databricks-sql-python/pull/96 merges.

**Pull request merged**
