### PR TITLE
Update Thrift package

### LINKED ISSUE #394: Unpin Thrift
Thrift version is currently pinned at `^0.16.0`, Thrift skipped all the way to `0.20.0` this year without any breaking changes in the [release notes](https://github.com/apache/thrift/blob/master/CHANGES.md) related to Python so it seems like it would be safe to upgrade.

### PR DESCRIPTION
**Pull request by m1n0**
Resolves #394

### CODE REVIEW

**Comment by m1n0** [comment]
This is a very simple change, could we get workflow approval for tests to run please?

**Review by susodapop — COMMENTED** [review]
This change LGTM.

**Review by kravets-levko — APPROVED** [review]

**Comment by m1n0** [comment]
Thanks for the review and approval! All tests fail on an seemingly unrelated error though, any advice?

**Comment by susodapop** [comment]
@m1n0 interesting! I checked out your branchy and tried the unit tests and everything passed. Looks like something changed on github that results in these failures.

**Comment by susodapop** [comment]
Looks like this is caused by a broader issue in virtualenv that is affecting many other developers: https://github.com/pypa/virtualenv/issues/2735

The solution is to force github actions to rebuild its virtualenvs (rather than caching them). I'm not quite clear how to force that since I can't see the GH Actions panel for this repo anymore. But this should be enough information to fix things, @kravets-levko

**Comment by susodapop** [comment]
Yep, the tests are failing because `actions/cache@v2` is pulling a cached version of the environment which was most recently rebuilt using a version of `filelock` that has since been yanked. [Here](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache) are the instructions for blowing away this cache so that GH Actions can rebuild it. This will cause the tests to pass.

**Comment by m1n0** [comment]
Thanks everyone!

**Pull request merged**
