### PR TITLE
Prepare release 3.2.0

### PR DESCRIPTION
**Pull request by kravets-levko**

### CODE REVIEW

**Review by yunbodeng-db — COMMENTED** [review]
What is the impact of "Relax `pyarrow` pin (databricks/databricks-sql-python#389 by @dhirschfeld)"?

**Comment by kravets-levko** [comment]
@yunbodeng-db it will allow users to use newer `pyarrow` version if they need

**Comment by dhirschfeld** [comment]
I'd really like to get the `pandas` pin relaxed too for the next release: https://github.com/databricks/databricks-sql-python/issues/342

**Review by yunbodeng-db — APPROVED** [review]

**Comment by m1n0** [comment]
Thrift is getting an update as well https://github.com/databricks/databricks-sql-python/commit/7ff60935cd9dc05f4dfb7a25dd6313da87bba68b

**Pull request merged**
