### PR TITLE
[PECO-1687] Fixed the issue of infinite blocking in case of invalid credentials

### PR DESCRIPTION
**Pull request by jprakash-db**
- Added the error handling for the Invalid Credentials error, that caused the connection retry to be stuck in an infinite loop

### CODE REVIEW

**Review by kravets-levko — CHANGES_REQUESTED** [review]
Hi @jprakash-db! Thank you for your effort on fixing this issue! Changes look good, but please do few things before we can merge this:

- remove `.idea` folder
- use existing `NonRecoverableNetworkError` instead of `AuthenticationFailureError`

**Comment by jprakash-db** [comment]
@kravets-levko Sure, I will make those changes

**Comment by kravets-levko** [comment]
@jprakash-db please also remove the `.idea` folder from this PR

**Comment by jprakash-db** [comment]
> @jprakash-db please also remove the `.idea` folder from this PR

Removed it @kravets-levko

**Comment by kravets-levko** [comment]
@jprakash-db Can you please resolve conflicts, so I can merge this PR? Thanks!

**Comment by jprakash-db** [comment]
@kravets-levko Resolved the merge conflicts

**Comment by kravets-levko** [comment]
@jprakash-db when you resolved conflicts, I got confused, because I clearly remember that your PR definitely contained a code for handing 401 status. And then, I realized that recently we merged databricks/databricks-sql-python#408 🤦‍♂️ Sorry for asking you to do the job which is no longer needed. Fortunately, such overlaps don't happen often

**Comment by jprakash-db** [comment]
@kravets-levko Ya, while merging I too saw, that someone had already fixed it 😅

**Pull request closed without merging**
