### PR TITLE
Disable non_native_boolean_check_constraint

### PR DESCRIPTION
**Pull request by bkyryliuk**
Disable non_native_boolean_check_constraint as it is not supported by databricks.
It is true by default: https://github.com/zzzeek/sqlalchemy/blob/main/lib/sqlalchemy/engine/default.py#L162

Tested via monkeypatching out code

error msg:
```
File /opt/miniconda3/envs/dev/lib/python3.9/site-packages/databricks/sql/thrift_backend.py:484, in ThriftBackend._check_command_not_in_error_or_closed_state(self, op_handle, get_operations_resp)
    482 if get_operations_resp.operationState == ttypes.TOperationState.ERROR_STATE:
    483     if get_operations_resp.displayMessage:
--> 484         raise ServerOperationError(
    485             get_operations_resp.displayMessage,
    486             {
    487                 "operation-id": op_handle and op_handle.operationId.guid,
    488                 "diagnostic-info": get_operations_resp.diagnosticInfo,
    489             },
    490         )
    491     else:
    492         raise ServerOperationError(
    493             get_operations_resp.errorMessage,
    494             {
   (...)
    497             },
    498         )

DatabaseError: (databricks.sql.exc.ServerOperationError)```

Generated ddl
```CREATE TABLE bogdan.__bogdan_test_1 (
	booli BOOLEAN,
	CHECK (booli IN (0, 1))
-^^^
) USING DELTA```

### CODE REVIEW

**Comment by susodapop** [comment]
The change LGTM. Please sign-off the commit as described in [CONTRIBUTING.md](https://github.com/databricks/databricks-sql-python/blob/main/CONTRIBUTING.md#sign-your-work)

> 
> Then you just add a line to every git commit message:
> 
>     Signed-off-by: Joe Smith <joe.smith@email.com>
> Use your real name (sorry, no pseudonyms or anonymous contributions.)
> If you set your user.name and user.email git configs, you can sign your commit automatically with git commit -s.

**Comment by bkyryliuk** [comment]
> The change LGTM. Please sign-off the commit as described in [CONTRIBUTING.md](https://github.com/databricks/databricks-sql-python/blob/main/CONTRIBUTING.md#sign-your-work)
> 
> > Then you just add a line to every git commit message:
> > ```
> > Signed-off-by: Joe Smith <joe.smith@email.com>
> > ```

> > Use your real name (sorry, no pseudonyms or anonymous contributions.)
> > If you set your user.name and user.email git configs, you can sign your commit automatically with git commit -s.

had a typo in the signature :)  fixed it

**Review by susodapop — APPROVED** [review]
All tests work for me. I need to push some changes to sync this back with `main` but it will merge today.

**Comment by susodapop** [comment]
Oh this is actually cool. I had to program something similar into our e2e tests when back-porting support for sqlalchemy==1.3.x. I wonder if I can remove those constraints now. I'm going to check that before I merge.

**Comment by susodapop** [comment]
Yessssss that worked.

**Pull request merged**
